force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Res-{000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Check_inDate__c.field-meta.xml
<CustomField>
    <fullName>Check_inDate__c</fullName>
    <label>Check-inDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_out_date__c.field-meta.xml
<CustomField>
    <fullName>Check_out_date__c</fullName>
    <label>Check-out date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Count_of_guests__c.field-meta.xml
<CustomField>
    <fullName>Count_of_guests__c</fullName>
    <label>Count of guests</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total_Price</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Maximum_guests__c.field-meta.xml
<CustomField>
    <fullName>Maximum_guests__c</fullName>
    <label>Maximum_count_of_guests</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Price_per_night__c.field-meta.xml
<CustomField>
    <fullName>Price_per_night__c</fullName>
    <label>Price_per_night</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RecordTypeControllerTest.cls
@isTest
global class RecordTypeControllerTest {

    
    @isTest global static void GetRecordTypeTest() {
        
         Hotel__c testHot = new Hotel__c (City__c = 'NY', Name = 'NY Hotel', Address__c = 'testAddress');
        insert testHot;
        
        Room__c testRoom = new Room__c (Name = 'King Room', Price_per_night__c = 54, Maximum_guests__c = 3, 
                                        Hotel__c = testHot.Id, Price__c = 432);
        insert testRoom;
        
        Reservation__c reservationTest = new Reservation__c(City__c = 'NY', Check_inDate__c = Date.newInstance(2019, 12, 29), 
                                                       Check_out_Date__c = Date.newInstance(2020, 01, 10), Count_of_guests__c = 2,
                                                       First_Name__c = 'Zhenya', Last_Name__c = 'Tit', Email_Address__c = 'sd@gmail.com',
                                                       Room__c = testRoom.Id, Total_Price__c = 100);
        
        insert reservationTest;
        
        Reservation__c reservationTest2 = new Reservation__c(City__c = 'NY', Check_inDate__c = Date.newInstance(2019, 12, 29), 
                                                       Check_out_Date__c = Date.newInstance(2020, 01, 10), Count_of_guests__c = 2,
                                                       First_Name__c = 'Zhenya', Last_Name__c = 'Tit', Email_Address__c = 'sd@gmail.com',
                                                       Room__c = testRoom.Id, Total_Price__c = 100, RecordTypeId = '0122v000002HTgiAAG');
        
        insert reservationTest2;

       String testResult = RecordTypeController.GetRecordType(reservationTest.Id);
       String testResult2 = RecordTypeController.GetRecordType(reservationTest2.Id);
    }
    
    @isTest global static void ChangeLabelTest() {
        
        Hotel__c testHot = new Hotel__c (City__c = 'NY', Name = 'NY Hotel', Address__c = 'testAddress');
        insert testHot;
        
        Room__c testRoom = new Room__c (Name = 'King Room', Price_per_night__c = 54, Maximum_guests__c = 3, 
                                        Hotel__c = testHot.Id, Price__c = 432);
        insert testRoom;
        
        Reservation__c reservationTest = new Reservation__c(City__c = 'NY', Check_inDate__c = Date.newInstance(2019, 12, 29), 
                                                       Check_out_Date__c = Date.newInstance(2020, 01, 10), Count_of_guests__c = 2,
                                                       First_Name__c = 'Zhenya', Last_Name__c = 'Tit', Email_Address__c = 'sd@gmail.com',
                                                       Room__c = testRoom.Id, Total_Price__c = 100);
        
        insert reservationTest;
        
        
       String testResult = RecordTypeController.ChangeLabel(reservationTest.Id);
        
    }
}